version: "3"

services:
  server:
    image: node
    expose:
      - "8080"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - server
    volumes:
      - ./nginx/default.conf:/etc/nginx/sites-available/default
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - "443:443"
      - "80:80"
